FROM node:12-alpine
ARG NODE_ENV=development
RUN echo $NODE_ENV
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --save --silent
COPY . .
RUN npm run build
CMD ["npm", "run","start"]